
#+title: The Inkwire Gazette - Issue #2
#+author: The Inkwell Gazette Editorial Board
* [ Today's Top Stories ]
** Brass Alley Marketplace Vendors Push Back Against Latest Curfew Rules
Brass Alley Marketplace vendors are making themselves heard, pushing back against a new emergency rule instituted by the Council of Creators against types of non-essential businesses running after 18:00.

The closures, as stated by Councilmember Offcinalis, will discourage people outside during the evening hours, which is when most disappearances reportedly have occurred. Future plans, the Councilmember continued, are in discussion as to how to compensate owners across the city for the disruption, but the business owners and stall runners of the Marketplace say that any plan will not be enough to compensate for the lost revenue.

Dozens have gathered in the City Circle, blocking access to the Grand Inventor's Hall's main entrance in the city circle to protest the rule.

"I rely on the evening rushes to make ends meet," reported one disgruntled protester, who said they own a ramen stall in the Marketplace. "No rush, no money! No money means I can't keep my stall running!"

The Inkwell Gazette has reached out to the Council for further comment on the issue, but has not recieved a response as of the publication of this article.

** Cogtown Family Dead After Attempting To Heat Ink In Apartment

A family of six has died after attempting to heat ink by using an exposed fire in their apartment, as reported by city officials.

Preliminary investigations by City Security and City Maintenance have concluded that the family died due to severe carbon monoxide poisoning, as the apartment was not properly ventilated enough to handle the fire.

City Maintenance took this opportunity to put out a public service announcement, alerting people to not tamper with the ink lines that run through buildings. Special emphasis was put on those still carrying ink still well above the superheated range, as the temperature could easily cause third and fourth-degree burns with minimal contact.

** City Security Arrests Potential Suspects In Inkfish-Trafficking Ring Behind Recent Disappearances

The Department of City Security has announced the arrest of eight individuals in suspicion of involvement with the recent disappearances within Tentacleton.

These individuals, all Octarian, are allegedly members of an criminal organization that has recently risen to prominent status within the City, due to its eccentric and famous leader: former commander-in-chief of the Octarian Army, Octavio.

The organization, often known as 'The Octoleet', first made their name by being attractive to former Octarian Army members, especially those who, for one reason or another, harbored ill-will against Inkadia and Inklings at large. At first they ran minor protection rackets, as well as smuggling illegal goods from Inkadia and the Splatlands. Various outcries to City Security for assistance had reportedly lead to dead ends, though, leading to rumors that some within the department are cooperating with the organization.

More recent reports indicate greater activity from The Octoleet, though, suggesting that they are seeking to become a greater power player in Tentacleton. Investigators within City Security suspect that the recent kidnappings may be relevant to this, although they have yet to discern any connection between those kidnapped, or a more detailed motive.
