#+TITLE: The Inkwire Gazette - Issue #1
* Continued Heat Shortages - Trend Getting Worse?
Continued reports of ink being significantly below temperature when pumped to the surface have been rising for the past several months, culminating in several buildings in the Manufacturing District being too insufficiently powered to operate. Steam pressure has also seen a remarkable fall in several key areas, notably in structures furthest away from the core of the Tentacleton Boilerworks.

Several of the City's leading experts have tried to speculate on what's going on, but without access to the Boilerworks, the cause is next to impossible to know with certainty. We have reached out to the Department of Infrastructure for comment, but received a similar response from them. However, they do wish to reassure the public that the Boilerworks are still far away from failing entirely, citing ink temperature and steam pressure trends that have been holding steady around The Inked Gear District and the Grand Inventor's Hall.

In spite of these numbers, though, people are still concerned. The greatest outcry has been from residents in the upper floors of the Cogtown Housing Project, whose heating has become unreliable enough to require manually burning fuel within fireplaces to heat ink.
* Redrise Emerges From Candidate Selection As Youngest Ascendant Councilmember
After several weeks of reportedly heated debate from within the Council Chamber, the newest member of the Council of Creators has been selected - a very new name to the Grand Inventor's Hall: Turquoise Redrise. The news has caused quite an upset among observers hoping to see one of the more established names take the recently-opened slot, but many still do offer their well wishes to the new member of Tentacleton's leadership.

"I hope to serve you all well!", spoke Councilmember Redrise from a press conference held in front of the Council Chamber's doors. "The fact that the rest of the Council has seen the promise in a young maker like me is an honor like no other! I hope in time to prove them right to all of you!"

At the age of 29, Redrise is set to be the youngest candidate to successfully ascend to the Council, taking the record from Councilmember Nicole Steeleman when she ascended at age 46. Concern regarding Redrise's inexperience has been a frequent subject of submissions to the Inkwire Gazette Newsroom, and some are even calling for an unprecedented redrawing of candidates.
* Disappearances On Sudden Rise, Reports City Security
Commissioner Hoylei has put out a statement alerting city residents of a recent string of missing persons cases that have come in over the past week, representing an alarming trend of what the Department of City Security suspects to be the rise of an organized inkfish-trafficking ring. Residents are advised to keep their awareness high in underpopulated sections of the City, and to stay within illuminated areas at night. Investigators are trying to determine what group may be behind this, as nearly every trail they have attempted to prod has produced no leads or suspects.

Commissioner Hoylei urges residents to report any leads or clues they may have to their local City Security Precinct Office, or to the Department of City Security directly.
